### ISSUE TITLE
well virustotal says that its not safe

### ISSUE THREAD

**Issue by xdzplays** [TheWation/PhpCookieStealer#2]
![Screenshot 2024-11-27 175351](https://github.com/user-attachments/assets/70077874-b24e-49cc-8e54-9b472fb736cd)

**Comment by xdzplays** [comment]
the .py is dangerous?

**Comment by xdzplays** [comment]
![Screenshot 2024-11-27 175922](https://github.com/user-attachments/assets/f6002eac-f113-42a3-9632-9096565b6ba7)

**Comment by xdzplays** [comment]
the neoware.py

**Comment by TheWation** [comment]
First, thank you for raising your concerns. However, there seems to be a misunderstanding:

1. This is PHP, not Python
The code in this repository is written in PHP, not Python, as evident from the file type and syntax.

2. This is Open Source Code
The code is open source, and anyone is free to review it. With fewer than 20 lines, it's simple enough to inspect and verify its functionality.

This script has a specific purpose in web penetration testing. If you are unfamiliar with its intended use, I strongly advise against running it without proper understanding and If you still have concerns or doubts, simply don’t use it.

**Comment by xdzplays** [comment]
k
